# using POSTMAN to test the API

### LOCAL HOST ### 
# localhost routes (3030 port) 

## BOOKS COLLECTION ##
# get all books
GET http://localhost:3030/books

# get book by id
# for example : The Tainted Cup 
# id : 673efe63f7dfab09ded11a4d
GET http://localhost:3030/books/673efe63f7dfab09ded11a4d

# create a new book
POST http://localhost:3030/books
{   "title": "Die with Zero",
    "subtitle": "Getting All You Can from Your Money and Your Life",
    "isbn": "9780358099765",
    "author": "Bill Perkins",
    "publisher": "Houghton Mifflin Harcourt",
    "publishedDate": "2020-07-28",
    "genre": "Finance"
}

# update a book
# for example : The Tainted Cup, change the subtitle from "Shadow of the Leviathan #1" to "Bitter Brews and Burning Hearts"
# id : 673efe63f7dfab09ded11a4d
PUT http://localhost:3030/books/673efe63f7dfab09ded11a4d
{   "title":"The Tainted Cup",
    "subtitle":"Shadow of the Leviathan #1",
    "isbn":"9781984820709",
    "author":"Robert Jackson Bennett",
    "publisher":"Del Rey",
    "publishedDate":"2024-02-06",
    "genre":"Fantasy"
}

# delete a book
# for example : The Tainted Cup
# id : 673efe63f7dfab09ded11a4d
DELETE http://localhost:3030/books/673efe63f7dfab09ded11a4d

## USERS COLLECTION ##
# get all users
GET http://localhost:3030/users

# get user by id
# for example : Aslan 
GET http://localhost:3030/users/6748864c8ff3efa1bf8ab318

# create a new user
# for example, Veihi
POST http://localhost:3030/users
{   "firstName": "Veihi",
    "lastName": "Mszp",
    "email": "veihim@gmail.com",
    "favoriteBooks": ["673f1982002928385a8b0734", "673f1982002928385a8b0734"],
    "githubId": "123456789",
    "username": "joy935"
}

# update a user
# for example : Aslan, change the email from "aslan@narnia.com" to "thelionking@narnia.com"
PUT http://localhost:3030/users/6748864c8ff3efa1bf8ab318
{   "firstName": "Aslan",
    "lastName": "Narnia",
    "email": "thelionking@narnia.com",
    "favoriteBooks": null,
    "githubId": "111111111",
    "username": "aslan"
}

# delete a user
# for example : Aslan
DELETE http://localhost:3030/users/6748864c8ff3efa1bf8ab318

### RENDER.COM ###

# get all books
GET https://cse341-project2-mszp.onrender.com/books

# get book by id
# for example : The Tainted Cup
# id : 673efe63f7dfab09ded11a4d
GET https://cse341-project2-mszp.onrender.com/books/673efe63f7dfab09ded11a4d

# create a new book
POST https://cse341-project2-mszp.onrender.com/books
{   "title": "Die with Zero",
    "subtitle": "Getting All You Can from Your Money and Your Life",
    "isbn": "9780358099765",
    "author": "Bill Perkins",
    "publisher": "Houghton Mifflin Harcourt",
    "publishedDate": "2020-07-28",
    "genre": "Finance"
}

# update a book
# for example : The Tainted Cup, change the subtitle from "Shadow of the Leviathan #1" to "Bitter Brews and Burning Hearts"
# id : 673efe63f7dfab09ded11a4d
PUT https://cse341-project2-mszp.onrender.com/books/673efe63f7dfab09ded11a4d
{   "title":"The Tainted Cup",
    "subtitle":"Shadow of the Leviathan #1",
    "isbn":"9781984820709",
    "author":"Robert Jackson Bennett",
    "publisher":"Del Rey",
    "publishedDate":"2024-02-06",
    "genre":"Fantasy"
}

# delete a book
# for example : The Tainted Cup
# id : 673efe63f7dfab09ded11a4d
DELETE https://cse341-project2-mszp.onrender.com/books/673efe63f7dfab09ded11a4d

## USERS COLLECTION ##
# get all users
GET http://cse341-project2-mszp.onrender.com/users

# get user by id
# for example : Aslan 
GET http://cse341-project2-mszp.onrender.com/users/6748864c8ff3efa1bf8ab318

# create a new user
# for example, Veihi
POST http://cse341-project2-mszp.onrender.com/users
{   "firstName": "Veihi",
    "lastName": "Mszp",
    "email": "veihim@gmail.com",
    "favoriteBooks": ["673f1982002928385a8b0734", "673f1982002928385a8b0734"],
    "githubId": "123456789",
    "username": "joy935"
}

# update a user
# for example : Aslan, change the email from "aslan@narnia.com" to "thelionking@narnia.com"
PUT http://cse341-project2-mszp.onrender.com/users/6748864c8ff3efa1bf8ab318
{   "firstName": "Aslan",
    "lastName": "Narnia",
    "email": "thelionking@narnia.com",
    "favoriteBooks": null,
    "githubId": "111111111",
    "username": "aslan"
}

# delete a user
# for example : Aslan
DELETE http://localhost:3030/users/6748864c8ff3efa1bf8ab318